### ISSUE TITLE
Warnings on cyres commands

### ISSUE THREAD

**Issue by kfhoech** [loonwerks/formal-methods-workbench#21]
!ENTRY org.eclipse.ui 2 0 2019-06-06 07:53:04.342
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2019-06-06 07:53:04.342
!MESSAGE Commands should really have a category: plug-in='com.collins.fmw.cyres.json.plugin', id='com.collins.fmw.cyres.json.commands.translate', categoryId='com.collins.fmw.cyres.json.commands'

!ENTRY org.eclipse.ui 2 0 2019-06-06 07:53:04.692
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2019-06-06 07:53:04.693
!MESSAGE Commands should really have a category: plug-in='com.collins.fmw.cyres.json.plugin', id='com.collins.fmw.cyres.json.commands.translate', categoryId='com.collins.fmw.cyres.json.commands'

**Comment by iamundson** [comment]
Fixed in commit 77ce4a7 on July 16 2019
